### ISSUE TITLE
Module not found after ./gerrit_stats.sh

### ISSUE THREAD

**Issue by janekolszak** [holmari/gerritstats#24] opened 2017-06-14 12:59 UTC
Hi! Great project, thank you so much for sharing!

I get some warnings when running `npm install` in GerritStats:
```
npm WARN redbox-react@1.4.2 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN redbox-react@1.4.2 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed.
npm WARN sass-loader@4.1.1 requires a peer of node-sass@^3.4.2 || ^4.0.0 but none was installed.
```

And then when running ./gerrit_stats.sh i get a looooot of `Module not found:`.

**Comment by janekolszak** [comment] 2017-06-14 14:05
I had to install bunch of modules to make it work.

**Comment by causten** [comment] 2017-07-11 18:42
How did you get past ...
Module not found: Error: Cannot resolve module 'd3-svg-legend/no-extend'

**Comment by janekolszak** [comment] 2017-07-12 08:16
Probably `npm install d3-svg-legend`

**Comment by holmari** [comment] 2017-07-12 08:43
Really sorry that I don't have time to maintain this project, I'm no longer working with Gerrit on a daily basis for almost a year now. Any PRs to fix issues or building new features are very welcome!

**Comment by causten** [comment] 2017-07-12 16:29
The newer version so d3-svg-legend do not have no-extend.  I had to down level to 1.13 to get past that error
npm install d3-svg-legend@1.13

That said, still not working so some other versions likely is not holding hands correctly.  Too bad, this tool looks great.    Console...
TypeError: _this.props.history is undefined[Learn More]  bundle.js:23556:8
GET 
http://localhost/~causten/out-html/bootstrap.css.map [HTTP/1.1 404 Not Found 18ms]

**Comment by guneshwor** [comment] 2017-07-21 16:08
Same here, index page is empty. Would want to know versions of all modules needed to make it work. Can someone help?

**Comment by guneshwor** [comment] 2017-07-21 16:33
FInally able to make it work after spending ~4 hours. Installed d3@3 and react-router@3.0.2 which solved last few issues

**Comment by holmari** [comment] 2017-07-21 17:07
@guneshwor Could you make a PR?

**Comment by guneshwor** [comment] 2017-07-21 17:37
Sure.

**Comment by holmari** [comment] 2017-07-22 09:29
I took a bit of time just now to take a look at these issues. @janekolszak, @causten, why do you have to install particular versions of the packages manually? `./gradlew assemble` should run the npm setup for you, and install all required packages in `GerritStats/node_modules` directory. Is that not working?

Meanwhile, I committed a package-lock.json file to master, which should also help resolving any dependency issues. Please try that out and let me know if it works.

**Comment by causten** [comment] 2017-07-24 15:01
Thank you.  I vote to close this issue as the problem is now fixed.  If you are ever in Austin Texas, I'll buy you a drink.

**Closed** 2017-07-25 12:22 UTC
